package com.onami.kagawacourses

data class Country(val name: String, val code: String, val flag: String)

fun getCountryList(): List<Country> {
    return listOf(
        Country("Afghanistan", "AF", "https://flagcdn.com/af.svg"),
        Country("Albania", "AL", "https://flagcdn.com/al.svg"),
        Country("Algeria", "DZ", "https://flagcdn.com/dz.svg"),
        Country("Andorra", "AD", "https://flagcdn.com/ad.svg"),
        Country("Angola", "AO", "https://flagcdn.com/ao.svg"),
        Country("Antigua and Barbuda", "AG", "https://flagcdn.com/ag.svg"),
        Country("Argentina", "AR", "https://flagcdn.com/ar.svg"),
        Country("Armenia", "AM", "https://flagcdn.com/am.svg"),
        Country("Australia", "AU", "https://flagcdn.com/au.svg"),
        Country("Austria", "AT", "https://flagcdn.com/at.svg"),
        Country("Azerbaijan", "AZ", "https://flagcdn.com/az.svg"),
        Country("Bahamas", "BS", "https://flagcdn.com/bs.svg"),
        Country("Bahrain", "BH", "https://flagcdn.com/bh.svg"),
        Country("Bangladesh", "BD", "https://flagcdn.com/bd.svg"),
        Country("Barbados", "BB", "https://flagcdn.com/bb.svg"),
        Country("Belarus", "BY", "https://flagcdn.com/by.svg"),
        Country("Belgium", "BE", "https://flagcdn.com/be.svg"),
        Country("Belize", "BZ", "https://flagcdn.com/bz.svg"),
        Country("Benin", "BJ", "https://flagcdn.com/bj.svg"),
        Country("Bhutan", "BT", "https://flagcdn.com/bt.svg"),
        Country("Bolivia", "BO", "https://flagcdn.com/bo.svg"),
        Country("Bosnia and Herzegovina", "BA", "https://flagcdn.com/ba.svg"),
        Country("Botswana", "BW", "https://flagcdn.com/bw.svg"),
        Country("Brazil", "BR", "https://flagcdn.com/br.svg"),
        Country("Brunei", "BN", "https://flagcdn.com/bn.svg"),
        Country("Bulgaria", "BG", "https://flagcdn.com/bg.svg"),
        Country("Burkina Faso", "BF", "https://flagcdn.com/bf.svg"),
        Country("Burundi", "BI", "https://flagcdn.com/bi.svg"),
        Country("Cabo Verde", "CV", "https://flagcdn.com/cv.svg"),
        Country("Cambodia", "KH", "https://flagcdn.com/kh.svg"),
        Country("Cameroon", "CM", "https://flagcdn.com/cm.svg"),
        Country("Canada", "CA", "https://flagcdn.com/ca.svg"),
        Country("Central African Republic", "CF", "https://flagcdn.com/cf.svg"),
        Country("Chad", "TD", "https://flagcdn.com/td.svg"),
        Country("Chile", "CL", "https://flagcdn.com/cl.svg"),
        Country("China", "CN", "https://flagcdn.com/cn.svg"),
        Country("Colombia", "CO", "https://flagcdn.com/co.svg"),
        Country("Comoros", "KM", "https://flagcdn.com/km.svg"),
        Country("Congo (Congo-Brazzaville)", "CG", "https://flagcdn.com/cg.svg"),
        Country("Costa Rica", "CR", "https://flagcdn.com/cr.svg"),
        Country("Croatia", "HR", "https://flagcdn.com/hr.svg"),
        Country("Cuba", "CU", "https://flagcdn.com/cu.svg"),
        Country("Cyprus", "CY", "https://flagcdn.com/cy.svg"),
        Country("Czechia (Czech Republic)", "CZ", "https://flagcdn.com/cz.svg"),
        Country("Denmark", "DK", "https://flagcdn.com/dk.svg"),
        Country("Djibouti", "DJ", "https://flagcdn.com/dj.svg"),
        Country("Dominica", "DM", "https://flagcdn.com/dm.svg"),
        Country("Dominican Republic", "DO", "https://flagcdn.com/do.svg"),
        Country("Ecuador", "EC", "https://flagcdn.com/ec.svg"),
        Country("Egypt", "EG", "https://flagcdn.com/eg.svg"),
        Country("El Salvador", "SV", "https://flagcdn.com/sv.svg"),
        Country("Equatorial Guinea", "GQ", "https://flagcdn.com/gq.svg"),
        Country("Eritrea", "ER", "https://flagcdn.com/er.svg"),
        Country("Estonia", "EE", "https://flagcdn.com/ee.svg"),
        Country("Eswatini", "SZ", "https://flagcdn.com/sz.svg"),
        Country("Ethiopia", "ET", "https://flagcdn.com/et.svg"),
        Country("Fiji", "FJ", "https://flagcdn.com/fj.svg"),
        Country("Finland", "FI", "https://flagcdn.com/fi.svg"),
        Country("France", "FR", "https://flagcdn.com/fr.svg"),
        Country("Gabon", "GA", "https://flagcdn.com/ga.svg"),
        Country("Gambia", "GM", "https://flagcdn.com/gm.svg"),
        Country("Georgia", "GE", "https://flagcdn.com/ge.svg"),
        Country("Germany", "DE", "https://flagcdn.com/de.svg"),
        Country("Ghana", "GH", "https://flagcdn.com/gh.svg"),
        Country("Greece", "GR", "https://flagcdn.com/gr.svg"),
        Country("Grenada", "GD", "https://flagcdn.com/gd.svg"),
        Country("Guatemala", "GT", "https://flagcdn.com/gt.svg"),
        Country("Guinea", "GN", "https://flagcdn.com/gn.svg"),
        Country("Guinea-Bissau", "GW", "https://flagcdn.com/gw.svg"),
        Country("Guyana", "GY", "https://flagcdn.com/gy.svg"),
        Country("Haiti", "HT", "https://flagcdn.com/ht.svg"),
        Country("Honduras", "HN", "https://flagcdn.com/hn.svg"),
        Country("Hungary", "HU", "https://flagcdn.com/hu.svg"),
        Country("Iceland", "IS", "https://flagcdn.com/is.svg"),
        Country("India", "IN", "https://flagcdn.com/in.svg"),
        Country("Indonesia", "ID", "https://flagcdn.com/id.svg"),
        Country("Iran", "IR", "https://flagcdn.com/ir.svg"),
        Country("Iraq", "IQ", "https://flagcdn.com/iq.svg"),
        Country("Ireland", "IE", "https://flagcdn.com/ie.svg"),
        Country("Israel", "IL", "https://flagcdn.com/il.svg"),
        Country("Italy", "IT", "https://flagcdn.com/it.svg"),
        Country("Jamaica", "JM", "https://flagcdn.com/jm.svg"),
        Country("Japan", "JP", "https://flagcdn.com/jp.svg"),
        Country("Jordan", "JO", "https://flagcdn.com/jo.svg"),
        Country("Kazakhstan", "KZ", "https://flagcdn.com/kz.svg"),
        Country("Kenya", "KE", "https://flagcdn.com/ke.svg"),
        Country("Kiribati", "KI", "https://flagcdn.com/ki.svg"),
        Country("Kuwait", "KW", "https://flagcdn.com/kw.svg"),
        Country("Kyrgyzstan", "KG", "https://flagcdn.com/kg.svg"),
        Country("Laos", "LA", "https://flagcdn.com/la.svg"),
        Country("Latvia", "LV", "https://flagcdn.com/lv.svg"),
        Country("Lebanon", "LB", "https://flagcdn.com/lb.svg"),
        Country("Lesotho", "LS", "https://flagcdn.com/ls.svg"),
        Country("Liberia", "LR", "https://flagcdn.com/lr.svg"),
        Country("Libya", "LY", "https://flagcdn.com/ly.svg"),
        Country("Liechtenstein", "LI", "https://flagcdn.com/li.svg"),
        Country("Lithuania", "LT", "https://flagcdn.com/lt.svg"),
        Country("Luxembourg", "LU", "https://flagcdn.com/lu.svg"),
        Country("Madagascar", "MG", "https://flagcdn.com/mg.svg"),
        Country("Malawi", "MW", "https://flagcdn.com/mw.svg"),
        Country("Malaysia", "MY", "https://flagcdn.com/my.svg"),
        Country("Maldives", "MV", "https://flagcdn.com/mv.svg"),
        Country("Mali", "ML", "https://flagcdn.com/ml.svg"),
        Country("Malta", "MT", "https://flagcdn.com/mt.svg"),
        Country("Marshall Islands", "MH", "https://flagcdn.com/mh.svg"),
        Country("Mauritania", "MR", "https://flagcdn.com/mr.svg"),
        Country("Mauritius", "MU", "https://flagcdn.com/mu.svg"),
        Country("Mexico", "MX", "https://flagcdn.com/mx.svg"),
        Country("Micronesia", "FM", "https://flagcdn.com/fm.svg"),
        Country("Moldova", "MD", "https://flagcdn.com/md.svg"),
        Country("Monaco", "MC", "https://flagcdn.com/mc.svg"),
        Country("Mongolia", "MN", "https://flagcdn.com/mn.svg"),
        Country("Montenegro", "ME", "https://flagcdn.com/me.svg"),
        Country("Morocco", "MA", "https://flagcdn.com/ma.svg"),
        Country("Mozambique", "MZ", "https://flagcdn.com/mz.svg"),
        Country("Myanmar (Burma)", "MM", "https://flagcdn.com/mm.svg"),
        Country("Namibia", "NA", "https://flagcdn.com/na.svg"),
        Country("Nauru", "NR", "https://flagcdn.com/nr.svg"),
        Country("Nepal", "NP", "https://flagcdn.com/np.svg"),
        Country("Netherlands", "NL", "https://flagcdn.com/nl.svg"),
        Country("New Zealand", "NZ", "https://flagcdn.com/nz.svg"),
        Country("Nicaragua", "NI", "https://flagcdn.com/ni.svg"),
        Country("Niger", "NE", "https://flagcdn.com/ne.svg"),
        Country("Nigeria", "NG", "https://flagcdn.com/ng.svg"),
        Country("North Korea", "KP", "https://flagcdn.com/kp.svg"),
        Country("North Macedonia", "MK", "https://flagcdn.com/mk.svg"),
        Country("Norway", "NO", "https://flagcdn.com/no.svg"),
        Country("Oman", "OM", "https://flagcdn.com/om.svg"),
        Country("Pakistan", "PK", "https://flagcdn.com/pk.svg"),
        Country("Palau", "PW", "https://flagcdn.com/pw.svg"),
        Country("Palestine", "PS", "https://flagcdn.com/ps.svg"),
        Country("Panama", "PA", "https://flagcdn.com/pa.svg"),
        Country("Papua New Guinea", "PG", "https://flagcdn.com/pg.svg"),
        Country("Paraguay", "PY", "https://flagcdn.com/py.svg"),
        Country("Peru", "PE", "https://flagcdn.com/pe.svg"),
        Country("Philippines", "PH", "https://flagcdn.com/ph.svg"),
        Country("Poland", "PL", "https://flagcdn.com/pl.svg"),
        Country("Portugal", "PT", "https://flagcdn.com/pt.svg"),
        Country("Qatar", "QA", "https://flagcdn.com/qa.svg"),
        Country("Romania", "RO", "https://flagcdn.com/ro.svg"),
        Country("Russia", "RU", "https://flagcdn.com/ru.svg"),
        Country("Rwanda", "RW", "https://flagcdn.com/rw.svg"),
        Country("Saint Kitts and Nevis", "KN", "https://flagcdn.com/kn.svg"),
        Country("Saint Lucia", "LC", "https://flagcdn.com/lc.svg"),
        Country("Saint Vincent and the Grenadines", "VC", "https://flagcdn.com/vc.svg"),
        Country("Samoa", "WS", "https://flagcdn.com/ws.svg"),
        Country("San Marino", "SM", "https://flagcdn.com/sm.svg"),
        Country("Sao Tome and Principe", "ST", "https://flagcdn.com/st.svg"),
        Country("Saudi Arabia", "SA", "https://flagcdn.com/sa.svg"),
        Country("Senegal", "SN", "https://flagcdn.com/sn.svg"),
        Country("Serbia", "RS", "https://flagcdn.com/rs.svg"),
        Country("Seychelles", "SC", "https://flagcdn.com/sc.svg"),
        Country("Sierra Leone", "SL", "https://flagcdn.com/sl.svg"),
        Country("Singapore", "SG", "https://flagcdn.com/sg.svg"),
        Country("Slovakia", "SK", "https://flagcdn.com/sk.svg"),
        Country("Slovenia", "SI", "https://flagcdn.com/si.svg"),
        Country("Solomon Islands", "SB", "https://flagcdn.com/sb.svg"),
        Country("Somalia", "SO", "https://flagcdn.com/so.svg"),
        Country("South Africa", "ZA", "https://flagcdn.com/za.svg"),
        Country("South Korea", "KR", "https://flagcdn.com/kr.svg"),
        Country("South Sudan", "SS", "https://flagcdn.com/ss.svg"),
        Country("Spain", "ES", "https://flagcdn.com/es.svg"),
        Country("Sri Lanka", "LK", "https://flagcdn.com/lk.svg"),
        Country("Sudan", "SD", "https://flagcdn.com/sd.svg"),
        Country("Suriname", "SR", "https://flagcdn.com/sr.svg"),
        Country("Sweden", "SE", "https://flagcdn.com/se.svg"),
        Country("Switzerland", "CH", "https://flagcdn.com/ch.svg"),
        Country("Syria", "SY", "https://flagcdn.com/sy.svg"),
        Country("Taiwan", "TW", "https://flagcdn.com/tw.svg"),
        Country("Tajikistan", "TJ", "https://flagcdn.com/tj.svg"),
        Country("Tanzania", "TZ", "https://flagcdn.com/tz.svg"),
        Country("Thailand", "TH", "https://flagcdn.com/th.svg"),
        Country("Timor-Leste", "TL", "https://flagcdn.com/tl.svg"),
        Country("Togo", "TG", "https://flagcdn.com/tg.svg"),
        Country("Tonga", "TO", "https://flagcdn.com/to.svg"),
        Country("Trinidad and Tobago", "TT", "https://flagcdn.com/tt.svg"),
        Country("Tunisia", "TN", "https://flagcdn.com/tn.svg"),
        Country("Turkey", "TR", "https://flagcdn.com/tr.svg"),
        Country("Turkmenistan", "TM", "https://flagcdn.com/tm.svg"),
        Country("Tuvalu", "TV", "https://flagcdn.com/tv.svg"),
        Country("Uganda", "UG", "https://flagcdn.com/ug.svg"),
        Country("Ukraine", "UA", "https://flagcdn.com/ua.svg"),
        Country("United Arab Emirates", "AE", "https://flagcdn.com/ae.svg"),
        Country("United Kingdom", "GB", "https://flagcdn.com/gb.svg"),
        Country("United States", "US", "https://flagcdn.com/us.svg"),
        Country("Uruguay", "UY", "https://flagcdn.com/uy.svg"),
        Country("Uzbekistan", "UZ", "https://flagcdn.com/uz.svg"),
        Country("Vanuatu", "VU", "https://flagcdn.com/vu.svg"),
        Country("Vatican City", "VA", "https://flagcdn.com/va.svg"),
        Country("Venezuela", "VE", "https://flagcdn.com/ve.svg"),
        Country("Vietnam", "VN", "https://flagcdn.com/vn.svg"),
        Country("Yemen", "YE", "https://flagcdn.com/ye.svg"),
        Country("Zambia", "ZM", "https://flagcdn.com/zm.svg"),
        Country("Zimbabwe", "ZW", "https://flagcdn.com/zw.svg")
    )
}
